
(declaim (optimize (speed 0) (safety 3) (space 0) (debug 3)))
(load "~/quicklisp/setup.lisp")
(ql:quickload 'alexandria)
(use-package 'alexandria)
(ql:quickload 'bordeaux-threads)
(ql:quickload 'cl-inotify)
(load "reflect.lisp")
(load "event.lisp")
(load "reloader.lisp")
(ql:quickload 'cffi)
(load "glfw3.lisp")
(ql:quickload 'cl-opengl)
(ql:quickload 'png)
(load "context-manager.lisp")
(load "window.lisp")
(load "shader-program.lisp")
(load "vertex-buffer.lisp")
(load "texture.lisp")
(load "test-context-manager.lisp")

